### ISSUE TITLE
The build in react native 0.40 is fail with the plugin installed

### ISSUE THREAD

**Issue by roysG** [stefalda/ReactNativeLocalization#59]
/Users/xxx/www/letsgout/public_html/test/node_modules/react-native-localization/ReactLocalization.m:39:67: error: property 'languageCode' not found on object of type 'NSLocale *'
        return [NSString stringWithFormat:@"%@-%@", currentLocale.languageCode, currentLocale.countryCode];

Why?

**Comment by stefalda** [comment]
Hi,
 just tested with a new project and version 0.40 and everything works smoothly.

What version of iOS are you using? I've tested with iOS 10.2.

Stefano

**Comment by adamfaryna** [comment]
@stefalda, there should mention in README that this lib requires IOS 10.0+. [API Reference](https://developer.apple.com/reference/foundation/nslocale/1643026-languagecode)

**Comment by stefalda** [comment]
@adamfaryna , after the latest modifications it should work even with previous version of the iOS SDK, that's the meaning of the code `SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"10")`
